name: "Deploy"

on:
  release:
    types: [published]

jobs:
  deploy:
    name: "Deploy to Neocities"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm install
      - run: npm run build
      - uses: kognise/neocel-action@v1
        with:
          neocities_token: ${{ secrets.NEOCITIES_TOKEN }}
          directory: "out/"
